// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Feedback struct {
	ID       string            `json:"id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	SurveyID string            `json:"surveyID"`
	UserID   string            `json:"userID"`
	Answers  []*FeedbackAnswer `json:"answers" gorm:"foreignKey:FeedbackID;references:ID"`
}

type FeedbackAnswer struct {
	ID         string `json:"id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	FeedbackID string `json:"feedbackID"`
	QuestionID string `json:"questionID"`
	Answer     int    `json:"answer"`
}

type FeedbackInput struct {
	QuestionID string `json:"questionID"`
	Answer     int    `json:"answer"`
}

type Mutation struct {
}

type Query struct {
}

type SubmitFeedbackInput struct {
	SurveyID string           `json:"surveyID"`
	UserID   string           `json:"userID"`
	Answers  []*FeedbackInput `json:"answers"`
}
