// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateSurveyInput struct {
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	Questions   []*QuestionInput `json:"questions"`
}

type Mutation struct {
}

type Option struct {
	ID         int    `json:"id" gorm:"primaryKey"`
	QuestionID string `json:"questionID"`
	OptionText string `json:"optionText"`
}

type OptionInput struct {
	OptionText string `json:"optionText"`
}

type Query struct {
}

type Question struct {
	ID           string    `json:"id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	SurveyID     string    `json:"surveyID"`
	QuestionText string    `json:"questionText"`
	Options      []*Option `json:"options" gorm:"foreignKey:QuestionID;references:ID"`
}

type QuestionInput struct {
	QuestionText string         `json:"questionText"`
	Options      []*OptionInput `json:"options"`
}

type Survey struct {
	ID          string      `json:"id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	Questions   []*Question `json:"questions" gorm:"foreignKey:SurveyID;references:ID"`
}
